// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApiAsincrona.Model;

namespace WebApiAsincrona.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20211228194714_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("WebApiAsincrona.Model.Alumno", b =>
                {
                    b.Property<int>("Expediente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("ApellidoM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApellidoP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("Delegado")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("FechaNac")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Expediente");

                    b.ToTable("Alumno");
                });

            modelBuilder.Entity("WebApiAsincrona.Model.Modulo", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Codigo");

                    b.ToTable("Modulo");
                });

            modelBuilder.Entity("WebApiAsincrona.Model.Modulo_Alumno", b =>
                {
                    b.Property<int>("IdModulo_Alumno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("AlumnoExpediente")
                        .HasColumnType("int");

                    b.Property<int>("Codigo_Alumno")
                        .HasColumnType("int");

                    b.Property<int>("Codigo_Modulo")
                        .HasColumnType("int");

                    b.Property<int?>("ModuloCodigo")
                        .HasColumnType("int");

                    b.HasKey("IdModulo_Alumno");

                    b.HasIndex("AlumnoExpediente");

                    b.HasIndex("ModuloCodigo");

                    b.ToTable("Modulo_Alumno");
                });

            modelBuilder.Entity("WebApiAsincrona.Model.Profesor", b =>
                {
                    b.Property<string>("RFC")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("ApellidoM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApellidoP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ModuloCodigo")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RFC");

                    b.HasIndex("ModuloCodigo");

                    b.ToTable("Profesor");
                });

            modelBuilder.Entity("WebApiAsincrona.Model.Modulo_Alumno", b =>
                {
                    b.HasOne("WebApiAsincrona.Model.Alumno", "Alumno")
                        .WithMany("Modulo_Alumno")
                        .HasForeignKey("AlumnoExpediente");

                    b.HasOne("WebApiAsincrona.Model.Modulo", "Modulo")
                        .WithMany("Modulo_Alumno")
                        .HasForeignKey("ModuloCodigo");

                    b.Navigation("Alumno");

                    b.Navigation("Modulo");
                });

            modelBuilder.Entity("WebApiAsincrona.Model.Profesor", b =>
                {
                    b.HasOne("WebApiAsincrona.Model.Modulo", "Modulo")
                        .WithMany("Profesor")
                        .HasForeignKey("ModuloCodigo");

                    b.Navigation("Modulo");
                });

            modelBuilder.Entity("WebApiAsincrona.Model.Alumno", b =>
                {
                    b.Navigation("Modulo_Alumno");
                });

            modelBuilder.Entity("WebApiAsincrona.Model.Modulo", b =>
                {
                    b.Navigation("Modulo_Alumno");

                    b.Navigation("Profesor");
                });
#pragma warning restore 612, 618
        }
    }
}
